import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Banner from "@/components/banner";
import Card from "@/components/Card/card";
import coffeeStoresData from "@/data/coffee-stores.json";
interface ICoffeeStores {
  id: string;
  name: string;
  imgUrl: string;
  websiteUrl: string;
  address: string;
  neighbourhood: string;
}
interface IHome {
  coffeeStores: ICoffeeStores[];
}

export async function getStaticProps() {
  console.log("Hi hello");
  return {
    props: {
      coffeeStores: coffeeStoresData,
    }, // will be passed to the page as props
  };
}

const Home: React.FC<IHome> = ({ coffeeStores }) => {
  const handleOnBannerBtnClick = () => {
    console.log("button clicked");
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Coffee Connoisseur</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Banner
          buttonText="View stores nearby"
          handleOnClick={handleOnBannerBtnClick}
        />
        <div className={styles.heroImage}>
          <Image
            src="/static/hero-image.png"
            width={700}
            height={400}
            alt="hero image"
          />
        </div>
        {coffeeStores.length > 0 && (
          <>
            <h2 className={styles.heading2}>Toronto Stores</h2>
            <div className={styles.cardLayout}>
              {coffeeStores.map((coffeeStore) => (
                <Card
                  key={coffeeStore.id}
                  imageUrl={coffeeStore.imgUrl}
                  name={coffeeStore.name}
                  href={`coffee-store/${coffeeStore.id}`}
                ></Card>
              ))}
            </div>
          </>
        )}
      </main>
    </div>
  );
};

export default Home;
